name: cong_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: ^3.3.0
  collection: ^1.17.2
  dropdown_button2: ^2.3.9
  flip_card: ^0.7.0
  floating_bottom_navigation_bar: 1.5.2
  flutter_animate: ^4.2.0+1
  flutter_cache_manager: ^3.3.1
  flutter_google_places: 
    git:
      url: https://github.com/fluttercommunity/flutter_google_places
      ref: v0.3.2
  flutter_plugin_android_lifecycle: ^2.0.16
  font_awesome_flutter: ^10.5.0
  from_css_color: 2.0.0
  geolocator: ^10.1.0
  geolocator_android: ^4.3.1
  geolocator_apple: ^2.3.2
  geolocator_platform_interface: ^4.1.1
  geolocator_web: ^2.2.0
  go_router: ^11.1.2
  google_fonts: ^4.0.4
  google_maps: 6.3.0
  google_maps_flutter: ^2.5.0
  google_maps_flutter_platform_interface: ^2.4.1
  google_maps_flutter_web: ^0.5.4+2
  intl: ^0.18.1
  json_path: ^0.6.6
  package_info_plus: ^4.1.0
  package_info_plus_platform_interface: 2.0.1
  page_transition: ^2.1.0
  path_provider: ^2.1.1
  path_provider_android: ^2.2.0
  path_provider_foundation: ^2.3.1
  path_provider_platform_interface: ^2.1.1
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  shared_preferences_android: ^2.2.1
  shared_preferences_ios: 2.1.1
  shared_preferences_platform_interface: ^2.3.1
  shared_preferences_web: ^2.2.1
  sqflite: ^2.3.0
  timeago: ^3.5.0
  url_launcher: ^6.1.14
  url_launcher_android: ^6.1.0
  url_launcher_ios: ^6.1.5
  url_launcher_platform_interface: ^2.1.5
  webview_flutter: ^4.4.1
  webview_flutter_android: ^3.12.0
  webview_flutter_platform_interface: ^2.6.0
  webview_flutter_wkwebview: ^3.9.1
  webviewx_plus: 0.3.3


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/

  fonts:
    - family: 'san francisco'
      fonts:
        - asset: assets/fonts/SFUIDisplay-Thin.otf
          weight: 100
        - asset: assets/fonts/SFUIDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/SFUIDisplay-Regular.otf
        - asset: assets/fonts/SFUIDisplay-Medium.otf
          weight: 500
        - asset: assets/fonts/SFUIDisplay-Semibold.otf
          weight: 600
        - asset: assets/fonts/SFUIDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFUIDisplay-Black.otf
          weight: 900


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
